import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { Command } from 'commander';
import type { MemoireEngine } from '../../engine/core.js';
const ports = vi.hoisted(() => ({ penpot: vi.fn(), audit: vi.fn() }));
vi.mock('../../figma/penpot-client.js',()=>({pullFromPenpot:ports.penpot}));
vi.mock('../../figma/wcag-token-checker.js',()=>({auditTokensForWcag:ports.audit}));
vi.mock('../../ai/index.js',()=>({hasAI:()=>false}));
import { registerPullCommand } from '../pull.js';
const token=(name:string,value='1')=>({name,collection:'Theme',type:'other',values:{default:value},cssVariable:`--${name}`});
const component=(name:string)=>({name,key:name,description:'',variants:[],properties:{},figmaNodeId:name});
const style=(name:string)=>({name,type:'fill',value:{color:'#000'}});
const empty=()=>({tokens:[] as ReturnType<typeof token>[],components:[] as ReturnType<typeof component>[],styles:[] as ReturnType<typeof style>[],lastSync:'fixture'});
function fixture() {
 const before=empty();const after=empty();const engine={init:vi.fn(async()=>{}),config:{figmaToken:undefined as string|undefined,figmaFileKey:undefined as string|undefined},figma:{isConnected:true},hasRunningBridge:vi.fn(async()=>false),ensureFigmaConnected:vi.fn(async()=>{}),pullDesignSystem:vi.fn(async()=>{}),pullDesignSystemREST:vi.fn(async()=>{}),snapshotDesignSystem:vi.fn().mockReturnValueOnce(before).mockReturnValue(after),registry:{designSystem:after,getAllSpecs:vi.fn(async()=>[{name:'A',type:'component',tags:['auto-generated']},{name:'B',type:'component'},{name:'P',type:'page',tags:[]}]),updateDesignSystem:vi.fn(async()=>{})}};
 const program=new Command();registerPullCommand(program,engine as unknown as MemoireEngine);return {engine,before,after,run:(...args:string[])=>program.parseAsync(['pull',...args],{from:'user'})};
}
let logs:ReturnType<typeof vi.spyOn>;
beforeEach(()=>{logs=vi.spyOn(console,'log').mockImplementation(()=>{});ports.penpot.mockReset();ports.audit.mockReset().mockReturnValue({hasFailures:false,summary:{total:1,pass:1,warn:0,fail:0},results:[]});for(const key of ['FIGMA_TOKEN','FIGMA_FILE_KEY','PENPOT_TOKEN','PENPOT_FILE_ID','PENPOT_BASE_URL'])vi.stubEnv(key,'');});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();process.exitCode=0;});
const output=()=>logs.mock.calls.map(args=>String(args[0])).join('\n');
const payload=()=>JSON.parse(String(logs.mock.calls.at(-1)?.[0]));
describe('pull release transport and result contract',()=>{
 it.each([false,true])('requires Penpot credentials before external calls (json=%s)',async json=>{const f=fixture();await f.run('--penpot',...(json?['--json']:[]));expect(ports.penpot).not.toHaveBeenCalled();expect(process.exitCode).toBe(1);expect(output()).toContain('required');});
 it.each([false,true])('persists successful Penpot results (json=%s)',async json=>{vi.stubEnv('PENPOT_TOKEN','synthetic');vi.stubEnv('PENPOT_FILE_ID','file');vi.stubEnv('PENPOT_BASE_URL','https://fixture.invalid');ports.penpot.mockResolvedValue({tokens:[token('a')],components:[component('Button')],styles:[],fileName:'Synthetic'});const f=fixture();await f.run('--penpot',...(json?['--json']:[]));expect(f.engine.registry.updateDesignSystem).toHaveBeenCalledWith(expect.objectContaining({tokens:[token('a')]}));expect(output()).toContain('Synthetic');});
 it.each([new Error('synthetic failure'),'string failure'])('reports Penpot failures without announcing completion: %s',async error=>{vi.stubEnv('PENPOT_TOKEN','synthetic');vi.stubEnv('PENPOT_FILE_ID','file');ports.penpot.mockRejectedValue(error);const f=fixture();await f.run('--penpot',...(typeof error==='string'?['--json']:[]));expect(process.exitCode).toBe(1);expect(f.engine.registry.updateDesignSystem).not.toHaveBeenCalled();expect(output()).toContain('failure');});
 it.each([false,true])('reports REST errors in explicit and early fallback paths (json=%s)',async json=>{for(const fallback of [false,true]){const f=fixture();f.engine.figma.isConnected=false;f.engine.config.figmaToken='synthetic';f.engine.config.figmaFileKey='file';f.engine.pullDesignSystemREST.mockRejectedValue('rest failure');await f.run(...(!fallback?['--rest']:[]),...(json?['--json']:[]));expect(process.exitCode).toBe(1);expect(output()).toContain('rest failure');expect(f.engine.pullDesignSystem).not.toHaveBeenCalled();}});
 it.each([false,true])('tries REST after a running bridge times out (json=%s)',async json=>{const f=fixture();f.engine.figma.isConnected=false;f.engine.hasRunningBridge.mockResolvedValue(true);f.engine.ensureFigmaConnected.mockRejectedValue(new Error('plugin timeout'));f.engine.config.figmaToken='synthetic';f.engine.config.figmaFileKey='file';await f.run(...(json?['--json']:[]));expect(f.engine.pullDesignSystemREST).toHaveBeenCalledWith(false);expect(f.engine.pullDesignSystem).not.toHaveBeenCalled();expect(output()).toContain(json?'completed':'REST');});
 it.each([false,true])('retains last-chance REST failure (json=%s)',async json=>{const f=fixture();f.engine.figma.isConnected=false;f.engine.hasRunningBridge.mockResolvedValue(true);f.engine.ensureFigmaConnected.mockRejectedValue('timeout');vi.stubEnv('FIGMA_TOKEN','synthetic');vi.stubEnv('FIGMA_FILE_KEY','file');f.engine.pullDesignSystemREST.mockRejectedValue(new Error('last chance failed'));await f.run(...(json?['--json']:[]));expect(process.exitCode).toBe(1);expect(output()).toContain('last chance failed');});
 it.each([false,true])('fails clearly without a plugin or REST credentials (json=%s)',async json=>{const f=fixture();f.engine.figma.isConnected=false;f.engine.ensureFigmaConnected.mockRejectedValue('unavailable');await f.run(...(json?['--json']:[]));expect(process.exitCode).toBe(1);expect(f.engine.pullDesignSystem).not.toHaveBeenCalled();});
 it('continues through a successfully reattached plugin and respects forced refresh',async()=>{const f=fixture();f.engine.figma.isConnected=false;await f.run('--force','--json');expect(f.engine.ensureFigmaConnected).toHaveBeenCalled();expect(f.engine.pullDesignSystem).toHaveBeenCalledWith(true);expect(payload()).toMatchObject({status:'completed',specs:{autoGenerated:1,total:3}});});
 it.each([false,true])('reports added/removed/changed tokens, components and styles (rest=%s)',async rest=>{for(const mode of ['added','removed','changed']){const f=fixture();if(mode==='added'){f.after.tokens=Array.from({length:22},(_,i)=>token(`new${i}`));f.after.components=[component('New')];f.after.styles=[style('New')];}else if(mode==='removed'){f.before.tokens=[token('Old')];f.before.components=[component('Old')];f.before.styles=[style('Old')];}else{f.before.tokens=[token('Same','1')];f.after.tokens=[token('Same','2')];f.before.components=[component('Same')];f.after.components=[{...component('Same'),description:'changed'}];f.before.styles=[style('Same')];f.after.styles=[{...style('Same'),value:{color:'#fff'}}];}await f.run(...(rest?['--rest']:[]));expect(output()).toContain('changed');if(!rest&&mode==='added')expect(output()).toContain('more');}});
 it.each([false,true])('returns WCAG failures as exit2 while preserving completed extraction (rest=%s)',async rest=>{for(const json of [false,true]){ports.audit.mockReturnValue({hasFailures:true,summary:{total:3,pass:1,warn:1,fail:1},results:[{status:'fail',tokenName:'Text',issue:'contrast',wcagCriterion:'1.4.3'},{status:'fail',tokenName:'Unknown'}]});const f=fixture();await f.run(...(rest?['--rest']:[]),'--wcag',...(json?['--json']:[]));expect(process.exitCode).toBe(2);if(json)expect(payload().status).toBe('completed');else expect(output()).toContain('FAIL');}});
 it('supports minimal engines without snapshots and zero automatic specs',async()=>{const f=fixture();f.engine.snapshotDesignSystem=undefined as never;f.engine.registry.getAllSpecs.mockResolvedValue([]);await f.run('--json');expect(payload().diff.hasChanges).toBe(false);const rest=fixture();rest.engine.snapshotDesignSystem=undefined as never;rest.engine.registry.getAllSpecs.mockResolvedValue([]);await rest.run('--rest');expect(output()).toContain('up to date');});
});
