/**
 * pull --rest stress tests — 20 conditions covering the REST pull flag,
 * error handling, JSON output, diff, and fallback to plugin mode.
 */

import { afterEach, describe, expect, it, vi } from "vitest";
import { Command } from "commander";
import { registerPullCommand } from "../pull.js";
import { captureLogs } from "./test-helpers.js";

vi.mock("../../engine/token-differ.js", () => ({
  diffDesignSystem: () => ({
    hasChanges: false,
    summary: "No changes",
    tokens: [],
    components: [],
    styles: [],
  }),
}));

afterEach(() => {
  vi.restoreAllMocks();
  process.exitCode = 0;
});

// ── Helpers ──────────────────────────────────────────────

function makeRestEngine(opts: {
  restSucceeds?: boolean;
  tokens?: number;
  components?: number;
  styles?: number;
  errorMsg?: string;
} = {}) {
  const { restSucceeds = true, tokens = 5, components = 3, styles = 2, errorMsg } = opts;
  const ds = {
    tokens: Array.from({ length: tokens }, (_, i) => ({ name: `token-${i}` })),
    components: Array.from({ length: components }, (_, i) => ({ name: `Comp${i}` })),
    styles: Array.from({ length: styles }, (_, i) => ({ name: `style-${i}` })),
    lastSync: new Date().toISOString(),
  };

  return {
    async init() {},
    figma: { isConnected: false },
    async pullDesignSystemREST() {
      if (!restSucceeds) throw new Error(errorMsg ?? "REST pull failed");
    },
    async pullDesignSystem() {},
    async ensureFigmaConnected() { throw new Error("No Figma plugin connected"); },
    registry: {
      designSystem: ds,
      async getAllSpecs() {
        return [
          { type: "component", name: "Comp0", tags: ["auto-generated"] },
          { type: "component", name: "Comp1", tags: [] },
        ];
      },
    },
    snapshotDesignSystem() { return { ...ds }; },
  };
}

// ── REST pull — success ───────────────────────────────────

describe("pull --rest — success", () => {
  it("calls pullDesignSystemREST not pullDesignSystem", async () => {
    const engine = makeRestEngine();
    const restSpy = vi.spyOn(engine, "pullDesignSystemREST");
    const pluginSpy = vi.spyOn(engine, "pullDesignSystem");
    captureLogs();
    const program = new Command();
    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--rest"], { from: "user" });
    expect(restSpy).toHaveBeenCalledOnce();
    expect(pluginSpy).not.toHaveBeenCalled();
  });

  it("does not attempt ensureFigmaConnected", async () => {
    const engine = makeRestEngine();
    const connectSpy = vi.spyOn(engine, "ensureFigmaConnected");
    captureLogs();
    const program = new Command();
    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--rest"], { from: "user" });
    expect(connectSpy).not.toHaveBeenCalled();
  });

  it("exits with code 0 on success", async () => {
    captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest"], { from: "user" });
    expect(process.exitCode).toBe(0);
  });

  it("does not throw or output JSON in default mode", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest"], { from: "user" });
    expect(logs.some((l) => l.includes("Done") || l.includes("tokens"))).toBe(true);
    expect(() => logs.forEach((l) => JSON.parse(l))).toThrow(); // not all lines are JSON
  });

  it("--rest --json outputs valid JSON payload", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(payload.status).toBe("completed");
  });

  it("--rest --json includes designSystem counts", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine({ tokens: 7, components: 4, styles: 2 }) as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(payload.designSystem.tokens).toBe(7);
    expect(payload.designSystem.components).toBe(4);
    expect(payload.designSystem.styles).toBe(2);
  });

  it("--rest --json includes specs count", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(typeof payload.specs.total).toBe("number");
    expect(typeof payload.specs.autoGenerated).toBe("number");
  });

  it("--rest --json includes elapsedMs", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(typeof payload.elapsedMs).toBe("number");
    expect(payload.elapsedMs).toBeGreaterThanOrEqual(0);
  });

  it("--rest --json figma.connected is false (no plugin used)", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(payload.figma.connected).toBe(false);
  });

  it("--rest --json includes diff field", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(payload.diff).toBeDefined();
    expect(typeof payload.diff.hasChanges).toBe("boolean");
  });

  it("--rest --json only emits one log line", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine() as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    expect(logs).toHaveLength(1);
  });
});

// ── REST pull — errors ────────────────────────────────────

describe("pull --rest — errors", () => {
  it("sets exitCode 1 on REST failure", async () => {
    captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine({ restSucceeds: false }) as never);
    await program.parseAsync(["pull", "--rest"], { from: "user" });
    expect(process.exitCode).toBe(1);
  });

  it("--rest --json emits failed payload on REST failure", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine({ restSucceeds: false, errorMsg: "FIGMA_TOKEN required" }) as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(payload.status).toBe("failed");
    expect(payload.error).toContain("FIGMA_TOKEN");
  });

  it("--rest --json failed payload has zero counts", async () => {
    const logs = captureLogs();
    const program = new Command();
    registerPullCommand(program, makeRestEngine({ restSucceeds: false }) as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    const payload = JSON.parse(logs.at(-1)!);
    expect(payload.designSystem.tokens).toBe(0);
    expect(payload.designSystem.components).toBe(0);
  });

  it("--rest failure without --json prints error to console.error", async () => {
    const errorLogs: string[] = [];
    vi.spyOn(console, "log").mockImplementation(() => {});
    vi.spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errorLogs.push(args.join(" "));
    });
    const program = new Command();
    registerPullCommand(program, makeRestEngine({ restSucceeds: false, errorMsg: "Bad token" }) as never);
    await program.parseAsync(["pull", "--rest"], { from: "user" });
    expect(errorLogs.some((l) => l.includes("Bad token") || l.includes("Error"))).toBe(true);
  });
});

// ── Plugin mode still works when --rest not passed ────────

describe("pull (plugin mode) — unaffected by --rest changes", () => {
  it("uses ensureFigmaConnected when --rest not passed and figma not connected", async () => {
    const engine = {
      async init() {},
      figma: { isConnected: false },
      async pullDesignSystem() {},
      async pullDesignSystemREST() {},
      async ensureFigmaConnected() { throw new Error("No plugin"); },
      registry: { designSystem: { tokens: [], components: [], styles: [], lastSync: "" }, async getAllSpecs() { return []; } },
      snapshotDesignSystem() { return { tokens: [], components: [], styles: [], lastSync: "" }; },
    };
    const connectSpy = vi.spyOn(engine, "ensureFigmaConnected");
    captureLogs();
    const program = new Command();
    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--json"], { from: "user" });
    expect(connectSpy).toHaveBeenCalled();
  });
});

// ── --rest --force ────────────────────────────────────────

describe("pull --rest --force", () => {
  it("passes force=true to pullDesignSystemREST", async () => {
    let capturedForce: boolean | undefined;
    const engine = {
      async init() {},
      figma: { isConnected: false },
      async pullDesignSystemREST(force?: boolean) { capturedForce = force; },
      async pullDesignSystem() {},
      async ensureFigmaConnected() {},
      registry: {
        designSystem: {
          tokens: [{ name: "t1" }],
          components: [],
          styles: [],
          lastSync: new Date().toISOString(),
        },
        async getAllSpecs() { return []; },
      },
      snapshotDesignSystem() { return { tokens: [], components: [], styles: [], lastSync: "" }; },
    };
    captureLogs();
    const program = new Command();
    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--rest", "--force", "--json"], { from: "user" });
    expect(capturedForce).toBe(true);
    expect(process.exitCode).toBeFalsy();
  });

  it("passes force=false to pullDesignSystemREST when --force not set", async () => {
    let capturedForce: boolean | undefined;
    const engine = {
      async init() {},
      figma: { isConnected: false },
      async pullDesignSystemREST(force?: boolean) { capturedForce = force; },
      async pullDesignSystem() {},
      async ensureFigmaConnected() {},
      registry: {
        designSystem: { tokens: [], components: [], styles: [], lastSync: "" },
        async getAllSpecs() { return []; },
      },
      snapshotDesignSystem() { return { tokens: [], components: [], styles: [], lastSync: "" }; },
    };
    captureLogs();
    const program = new Command();
    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--rest", "--json"], { from: "user" });
    expect(capturedForce).toBe(false);
  });

  it("JSON output includes status:completed after forced REST pull", async () => {
    const logs = captureLogs();
    const engine = {
      async init() {},
      figma: { isConnected: false },
      async pullDesignSystemREST(_force?: boolean) {},
      async pullDesignSystem() {},
      async ensureFigmaConnected() {},
      registry: {
        designSystem: { tokens: [{ name: "tok" }], components: [], styles: [], lastSync: "" },
        async getAllSpecs() { return []; },
      },
      snapshotDesignSystem() { return { tokens: [], components: [], styles: [], lastSync: "" }; },
    };
    const program = new Command();
    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--rest", "--force", "--json"], { from: "user" });
    const payload = JSON.parse(logs.join(""));
    expect(payload.status).toBe("completed");
    expect(payload.designSystem.tokens).toBe(1);
  });
});
