import type { Command } from "commander";
import type { MemoireEngine } from "../engine/core.js";
import { checkCapabilities, formatCapabilityError } from "../engine/capabilities.js";
import { diffDesignSystem } from "../engine/token-differ.js";
import { ui } from "../tui/format.js";
import { auditTokensForWcag, type WcagTokenReport } from "../figma/wcag-token-checker.js";
import { pullFromPenpot } from "../figma/penpot-client.js";

export interface PullPayload {
  status: "completed" | "failed";
  figma: {
    connected: boolean;
  };
  designSystem: {
    tokens: number;
    components: number;
    styles: number;
  };
  specs: {
    autoGenerated: number;
    total: number;
  };
  elapsedMs: number;
  error?: string;
  wcagReport?: WcagTokenReport;
}

/** Shared REST pull logic — used by --rest flag and auto-fallback */
async function executeRestPull(
  engine: MemoireEngine,
  opts: { json?: boolean; wcag?: boolean; force?: boolean },
  start: number,
  via: "flag" | "fallback" = "flag",
): Promise<void> {
  if (!opts.json) {
    const label = via === "fallback"
      ? "No Figma plugin connected — using REST API"
      : "Pulling via REST API";
    console.log(`\n  ${label}${opts.force ? " (forced)" : ""}...\n`);
    if (via === "fallback") {
      console.log("  Tip: run `memi connect --background` for real-time plugin sync\n");
    }
  }

  const before = engine.snapshotDesignSystem?.() ?? { tokens: [], components: [], styles: [], lastSync: "" };
  await engine.pullDesignSystemREST(opts.force ?? false);
  const ds = engine.registry.designSystem;
  const specs = await engine.registry.getAllSpecs();
  const autoSpecs = specs.filter((s) => s.type === "component" && s.tags?.includes("auto-generated"));

  const payload: PullPayload = {
    status: "completed",
    figma: { connected: false },
    designSystem: { tokens: ds.tokens.length, components: ds.components.length, styles: ds.styles.length },
    specs: { autoGenerated: autoSpecs.length, total: specs.length },
    elapsedMs: Date.now() - start,
  };

  if (opts.wcag) {
    const wcagReport = auditTokensForWcag(ds.tokens);
    payload.wcagReport = wcagReport;
    if (wcagReport.hasFailures) process.exitCode = 2;
  }

  const after = engine.snapshotDesignSystem?.() ?? ds;
  const diff = diffDesignSystem(before, after);

  if (opts.json) {
    (payload as unknown as Record<string, unknown>).diff = {
      hasChanges: diff.hasChanges,
      summary: diff.summary,
      tokens: diff.tokens.length,
      components: diff.components.length,
      styles: diff.styles.length,
    };
    console.log(JSON.stringify(payload, null, 2));
    return;
  }

  console.log(`  Done. Design system saved to .memoire/design-system.json`);

  // Diff summary
  if (diff.hasChanges) {
    const tokenAdded = diff.tokens.filter((c) => c.type === "added").length;
    const tokenRemoved = diff.tokens.filter((c) => c.type === "removed").length;
    const compAdded = diff.components.filter((c) => c.type === "added").length;
    const compRemoved = diff.components.filter((c) => c.type === "removed").length;
    const stylesAdded = diff.styles.filter((c) => c.type === "added").length;
    const stylesRemoved = diff.styles.filter((c) => c.type === "removed").length;
    const tokenDiff = tokenAdded > 0 ? `+${tokenAdded}` : tokenRemoved > 0 ? `-${tokenRemoved}` : "0";
    const compDiff = compAdded > 0 ? `+${compAdded}` : compRemoved > 0 ? `-${compRemoved}` : "0";
    const stylesDiff = stylesAdded > 0 ? `+${stylesAdded}` : stylesRemoved > 0 ? `-${stylesRemoved}` : "0";
    console.log(`  ${tokenDiff} tokens, ${compDiff} components, ${stylesDiff} styles changed`);
  } else {
    console.log("  Design system up to date");
  }

  if (autoSpecs.length > 0) {
    console.log(`  Auto-generated ${autoSpecs.length} component specs — run \`memi generate\` to create code`);
  }
  if (opts.wcag && payload.wcagReport) {
    printWcagReport(payload.wcagReport);
  }
  console.log("");
}

export function registerPullCommand(program: Command, engine: MemoireEngine) {
  program
    .command("pull")
    .description("Pull design system from Figma. Auto-falls back to REST API when no plugin is connected.")
    .option("--rest", "Force pull via Figma REST API (no plugin required — needs FIGMA_TOKEN + FIGMA_FILE_KEY)")
    .option("--penpot", "Pull from Penpot (needs PENPOT_TOKEN + PENPOT_FILE_ID + PENPOT_BASE_URL)")
    .option("--force", "Bypass the 5-minute pull cache and force a fresh pull")
    .option("--json", "Output pull results as JSON")
    .option("--wcag", "Run WCAG token audit after pull. Sets exit code 2 when failures are found.")
    .action(async (opts: { rest?: boolean; penpot?: boolean; force?: boolean; json?: boolean; wcag?: boolean }) => {
      const start = Date.now();
      await engine.init();

      // ── Penpot pull ─────────────────────────────────────────
      if (opts.penpot) {
        const penpotToken = process.env.PENPOT_TOKEN;
        const penpotFileId = process.env.PENPOT_FILE_ID;
        const penpotBase = process.env.PENPOT_BASE_URL ?? "https://design.penpot.app";

        if (!penpotToken || !penpotFileId) {
          const msg = "PENPOT_TOKEN and PENPOT_FILE_ID are required for --penpot pull";
          if (opts.json) {
            console.log(JSON.stringify({ status: "failed", error: msg }));
          } else {
            console.log(ui.fail(msg));
            console.log("  export PENPOT_TOKEN=your-token");
            console.log("  export PENPOT_FILE_ID=your-file-uuid");
            console.log("  export PENPOT_BASE_URL=https://design.penpot.app  # or self-hosted URL");
            console.log();
          }
          process.exitCode = 1;
          return;
        }

        if (!opts.json) console.log("\n  Pulling from Penpot...\n");
        try {
          const result = await pullFromPenpot({ baseUrl: penpotBase, token: penpotToken, fileId: penpotFileId });
          await engine.registry.updateDesignSystem({
            tokens: result.tokens,
            components: result.components,
            styles: result.styles,
            lastSync: new Date().toISOString(),
          });
          if (opts.json) {
            console.log(JSON.stringify({ status: "completed", source: "penpot", fileName: result.fileName, designSystem: { tokens: result.tokens.length, components: result.components.length, styles: result.styles.length }, elapsedMs: Date.now() - start }, null, 2));
          } else {
            console.log(`  ${result.tokens.length} tokens, ${result.components.length} components from "${result.fileName}"`);
            console.log("  Run `memi generate` to generate code from specs\n");
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (opts.json) {
            console.log(JSON.stringify({ status: "failed", source: "penpot", error: msg }));
          } else {
            console.log(ui.fail(`Penpot error: ${msg}`));
            console.log();
          }
          process.exitCode = 1;
        }
        return;
      }

      // Explicit REST mode
      if (opts.rest) {
        try {
          await executeRestPull(engine, opts, start, "flag");
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (opts.json) {
            console.log(JSON.stringify({ status: "failed", figma: { connected: false }, designSystem: { tokens: 0, components: 0, styles: 0 }, specs: { autoGenerated: 0, total: 0 }, elapsedMs: Date.now() - start, error: msg } satisfies PullPayload, null, 2));
          } else {
            console.log(ui.fail(`Error: ${msg}`));
            console.log();
          }
          process.exitCode = 1;
        }
        return;
      }

      // Bridge path — auto-fallback to REST if no bridge is running
      if (!engine.figma?.isConnected) {
        const bridgeRunning = await engine.hasRunningBridge();

        if (!bridgeRunning) {
          // No bridge process at all — check for REST credentials before waiting
          const hasToken = !!(engine.config.figmaToken || process.env.FIGMA_TOKEN);
          const hasFileKey = !!(engine.config.figmaFileKey || process.env.FIGMA_FILE_KEY);

          if (hasToken && hasFileKey) {
            try {
              await executeRestPull(engine, opts, start, "fallback");
            } catch (err) {
              const msg = err instanceof Error ? err.message : String(err);
              if (opts.json) {
                console.log(JSON.stringify({ status: "failed", figma: { connected: false }, designSystem: { tokens: 0, components: 0, styles: 0 }, specs: { autoGenerated: 0, total: 0 }, elapsedMs: Date.now() - start, error: msg } satisfies PullPayload, null, 2));
              } else {
                console.log(ui.fail(`Error: ${msg}`));
                console.log();
              }
              process.exitCode = 1;
            }
            return;
          }
        }

        // Bridge is running (or no REST creds) — wait for plugin
        const caps = checkCapabilities("pull", {
          figma: false,
          ai: !!process.env.ANTHROPIC_API_KEY,
          specs: false,
          generatedCode: false,
          research: false,
          daemon: false,
        });

        try {
          await engine.ensureFigmaConnected();
        } catch (err) {
          // Plugin timed out — last-chance REST fallback
          const hasToken = !!(engine.config.figmaToken || process.env.FIGMA_TOKEN);
          const hasFileKey = !!(engine.config.figmaFileKey || process.env.FIGMA_FILE_KEY);

          if (hasToken && hasFileKey) {
            if (!opts.json) console.log("\n  Plugin did not respond — falling back to REST API...\n");
            try {
              await executeRestPull(engine, opts, start, "fallback");
            } catch (restErr) {
              const msg = restErr instanceof Error ? restErr.message : String(restErr);
              if (opts.json) {
                console.log(JSON.stringify({ status: "failed", figma: { connected: false }, designSystem: { tokens: 0, components: 0, styles: 0 }, specs: { autoGenerated: 0, total: 0 }, elapsedMs: Date.now() - start, error: msg } satisfies PullPayload, null, 2));
              } else {
                console.log(ui.fail(`Error: ${msg}`));
                console.log();
              }
              process.exitCode = 1;
            }
            return;
          }

          const msg = err instanceof Error ? err.message : String(err);
          if (opts.json) {
            console.log(JSON.stringify({ status: "failed", figma: { connected: false }, designSystem: { tokens: 0, components: 0, styles: 0 }, specs: { autoGenerated: 0, total: 0 }, elapsedMs: Date.now() - start, error: msg } satisfies PullPayload, null, 2));
            process.exitCode = 1;
            return;
          }
          console.log(formatCapabilityError(caps, "pull"));
          process.exitCode = 1;
          return;
        }
      }

      // Snapshot before pull for diff
      const before = engine.snapshotDesignSystem?.() ?? { tokens: [], components: [], styles: [], lastSync: "" };

      if (!opts.json) console.log(`\n  Pulling design system${opts.force ? " (forced)" : ""}...\n`);
      await engine.pullDesignSystem(opts.force ?? false);

      const specs = await engine.registry.getAllSpecs();
      const autoSpecs = specs.filter((s) => s.type === "component" && s.tags?.includes("auto-generated"));
      const ds = engine.registry.designSystem;

      const payload: PullPayload = {
        status: "completed",
        figma: { connected: true },
        designSystem: {
          tokens: ds.tokens.length,
          components: ds.components.length,
          styles: ds.styles.length,
        },
        specs: {
          autoGenerated: autoSpecs.length,
          total: specs.length,
        },
        elapsedMs: Date.now() - start,
      };

      // Compute diff
      const after = engine.snapshotDesignSystem?.() ?? engine.registry.designSystem;
      const diff = diffDesignSystem(before, after);

      // WCAG audit — plugin path
      if (opts.wcag) {
        const wcagReport = auditTokensForWcag(ds.tokens);
        payload.wcagReport = wcagReport;
        if (wcagReport.hasFailures) process.exitCode = 2;
      }

      if (opts.json) {
        (payload as unknown as Record<string, unknown>).diff = {
          hasChanges: diff.hasChanges,
          summary: diff.summary,
          tokens: diff.tokens.length,
          components: diff.components.length,
          styles: diff.styles.length,
        };
        console.log(JSON.stringify(payload, null, 2));
        return;
      }

      console.log(`\n  Done. Design system saved to .memoire/design-system.json`);

      // Show diff
      if (diff.hasChanges) {
        const tokenAdded = diff.tokens.filter((c) => c.type === "added").length;
        const tokenRemoved = diff.tokens.filter((c) => c.type === "removed").length;
        const compAdded = diff.components.filter((c) => c.type === "added").length;
        const compRemoved = diff.components.filter((c) => c.type === "removed").length;
        const stylesAdded = diff.styles.filter((c) => c.type === "added").length;
        const stylesRemoved = diff.styles.filter((c) => c.type === "removed").length;
        const tokenDiff = tokenAdded > 0 ? `+${tokenAdded}` : tokenRemoved > 0 ? `-${tokenRemoved}` : "0";
        const compDiff = compAdded > 0 ? `+${compAdded}` : compRemoved > 0 ? `-${compRemoved}` : "0";
        const stylesDiff = stylesAdded > 0 ? `+${stylesAdded}` : stylesRemoved > 0 ? `-${stylesRemoved}` : "0";
        console.log(`  ${tokenDiff} tokens, ${compDiff} components, ${stylesDiff} styles changed`);
        console.log();
        if (diff.tokens.length > 0) {
          console.log("  TOKENS");
          for (const c of diff.tokens.slice(0, 20)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
          if (diff.tokens.length > 20) console.log(`    ${ui.dim(`... and ${diff.tokens.length - 20} more`)}`);
        }
        if (diff.components.length > 0) {
          console.log("  COMPONENTS");
          for (const c of diff.components.slice(0, 10)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
        }
        if (diff.styles.length > 0) {
          console.log("  STYLES");
          for (const c of diff.styles.slice(0, 10)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
        }
        console.log();
      } else {
        console.log("  Design system up to date");
      }

      if (autoSpecs.length > 0) {
        console.log(`  Auto-generated ${autoSpecs.length} component specs — run \`memi generate\` to create code`);
      }

      if (opts.wcag && payload.wcagReport) {
        printWcagReport(payload.wcagReport);
      }

      console.log("");
    });
}

/**
 * Print a human-readable WCAG token audit summary to stdout.
 * Failures are printed individually with token name, value, and ratio.
 */
function printWcagReport(report: WcagTokenReport): void {
  const { summary, results } = report;
  console.log();
  console.log(`  wcag audit  ${summary.total} tokens checked`);
  console.log(`  [pass]  ${String(summary.pass).padStart(2)}  no issues`);
  if (summary.warn > 0) {
    console.log(`  [warn]  ${String(summary.warn).padStart(2)}  low contrast (AA-large only)`);
  }
  if (summary.fail > 0) {
    console.log(`  [fail]  ${String(summary.fail).padStart(2)}  inaccessible`);
    console.log();
    for (const r of results.filter((r) => r.status === "fail")) {
      console.log(`    FAIL  ${r.tokenName}  ${r.issue ?? ""}  [${r.wcagCriterion ?? ""}]`);
    }
  }
}
