import type { Command } from "commander";
import type { MemoireEngine } from "../engine/core.js";
import { checkCapabilities, formatCapabilityError } from "../engine/capabilities.js";
import { diffDesignSystem } from "../engine/token-differ.js";
import { ui } from "../tui/format.js";

export interface PullPayload {
  status: "completed" | "failed";
  figma: {
    connected: boolean;
  };
  designSystem: {
    tokens: number;
    components: number;
    styles: number;
  };
  specs: {
    autoGenerated: number;
    total: number;
  };
  elapsedMs: number;
  error?: string;
}

export function registerPullCommand(program: Command, engine: MemoireEngine) {
  program
    .command("pull")
    .description("Pull design system from connected Figma file")
    .option("--json", "Output pull results as JSON")
    .action(async (opts: { json?: boolean }) => {
      const start = Date.now();
      await engine.init();

      // Check capabilities before attempting connection
      const caps = checkCapabilities("pull", {
        figma: engine.figma?.isConnected ?? false,
        ai: !!process.env.ANTHROPIC_API_KEY,
        specs: false,
        generatedCode: false,
        research: false,
        daemon: false,
      });

      if (!caps.ok && !engine.figma?.isConnected) {
        // Try to connect first
        try {
          await engine.ensureFigmaConnected();
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (opts.json) {
            const payload: PullPayload = {
              status: "failed",
              figma: { connected: false },
              designSystem: { tokens: 0, components: 0, styles: 0 },
              specs: { autoGenerated: 0, total: 0 },
              elapsedMs: Date.now() - start,
              error: msg,
            };
            console.log(JSON.stringify(payload, null, 2));
            process.exitCode = 1;
            return;
          }
          console.error(formatCapabilityError(caps, "pull"));
          process.exitCode = 1;
          return;
        }
      }

      // Snapshot before pull for diff
      const before = engine.snapshotDesignSystem?.() ?? { tokens: [], components: [], styles: [], lastSync: "" };

      if (!opts.json) console.log("\n  Pulling design system...\n");
      await engine.pullDesignSystem();

      const specs = await engine.registry.getAllSpecs();
      const autoSpecs = specs.filter((s) => s.type === "component" && s.tags?.includes("auto-generated"));
      const ds = engine.registry.designSystem;

      const payload: PullPayload = {
        status: "completed",
        figma: { connected: true },
        designSystem: {
          tokens: ds.tokens.length,
          components: ds.components.length,
          styles: ds.styles.length,
        },
        specs: {
          autoGenerated: autoSpecs.length,
          total: specs.length,
        },
        elapsedMs: Date.now() - start,
      };

      // Compute diff
      const after = engine.snapshotDesignSystem?.() ?? engine.registry.designSystem;
      const diff = diffDesignSystem(before, after);

      if (opts.json) {
        (payload as unknown as Record<string, unknown>).diff = {
          hasChanges: diff.hasChanges,
          summary: diff.summary,
          tokens: diff.tokens.length,
          components: diff.components.length,
          styles: diff.styles.length,
        };
        console.log(JSON.stringify(payload, null, 2));
        return;
      }

      console.log(`\n  Done. Design system saved to .memoire/design-system.json`);

      // Show diff
      if (diff.hasChanges) {
        console.log();
        if (diff.tokens.length > 0) {
          console.log("  TOKENS");
          for (const c of diff.tokens.slice(0, 20)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
          if (diff.tokens.length > 20) console.log(`    ${ui.dim(`... and ${diff.tokens.length - 20} more`)}`);
        }
        if (diff.components.length > 0) {
          console.log("  COMPONENTS");
          for (const c of diff.components.slice(0, 10)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
        }
        if (diff.styles.length > 0) {
          console.log("  STYLES");
          for (const c of diff.styles.slice(0, 10)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
        }
        console.log();
        console.log(`  ${diff.summary}`);
      } else {
        console.log("  No changes detected.");
      }

      if (autoSpecs.length > 0) {
        console.log(`  Auto-generated ${autoSpecs.length} component specs — run \`memi generate\` to create code`);
      }
      console.log("");
    });
}
